name: Initialize project
on:
  create:
    branches: [main]
jobs:
  build:
    name: "Remove unnecessary files"
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2
      - name: Delete files
        run: |
          rm -rf .editorconfig .github
      - name: Git Commit/Push Changes
        uses: actions-x/commit@v1
